let keyButtons = [
  "Backquote",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Digit0",
  "Minus",
  "Equal",
  "Backspace",
  "Tab",
  "KeyQ",
  "KeyW",
  "KeyE",
  "KeyR",
  "KeyT",
  "KeyY",
  "KeyU",
  "KeyI",
  "KeyO",
  "KeyP",
  "BracketLeft",
  "BracketRight",
  "Backslash",
  "CapsLock",
  "KeyA",
  "KeyS",
  "KeyD",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyJ",
  "KeyK",
  "KeyL",
  "Semicolon",
  "Quote",
  "ShiftLeft",
  "KeyZ",
  "KeyX",
  "KeyC",
  "KeyV",
  "KeyB",
  "KeyN",
  "KeyM",
  "Comma",
  "Period",
  "Space",
];
let textPera = [
  "Hello everyOne",
  "Hello guys",
  "Hello man",
//   " Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti a at sequi, fugit corporis itaque ex, iure cumque exercitationem necessitatibus eligendi. Doloremque, quos nam vitae iure illo tempora totam quis.",
//   "   Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis veritatis iusto minima qui fugit eos nemo magni aliquam voluptates dolores.",
//   " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et, iusto.",
];

export {keyButtons , textPera}
